services:
  phpinfo:
    command:
      - php
      - -f
      - index.php
      - -S
      - 0.0.0.0:8081
    image: docker.io/library/php:alpine
    ports:
      - 8080
    volumes:
      - /tmp/phpinfo:/phpinfo
    working_dir: /phpinfo
version: "3.8"
